deployment: # used only if knativeServing.use: false
  name: helloworld-nodejs
  namespace: default
  replicaCount: 2
  containerPort: 8080
  nodeEnv: development

service:
  type: ClusterIP
  port: 80

image:
  hub: registry-vpc.cn-hongkong.aliyuncs.com
  repository: infra/devops-argocd-test
  tag: helloworld-nodejs

secret:
  dockerCredentials: docker-credentials

tekton:
  Pipeline:
    name: helloworld-nodejs
    workspaces:
      name: shared-data
  Source:
    name: tekton-basic-nodejs-app
    gitUrl: https://github.com/ericwinn/tekton-basic-nodejs-app.git